name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: |
        set -e
        docker buildx create --use
        for item in $(ls); do
          if [ -d ${item} ] && [ -f ${item}/Dockerfile ]; then
            docker_tag=${{ secrets.DOCKERHUB_USERNAME }}/stacksmith-${item}
            cache_docker_tag=${{ env.REGISTRY }}/${{ github.repository }}/${item}
            docker buildx build ${item} \
              --pull \
              --push \
              --cache-from type=registry,ref=${cache_docker_tag}:cache \
              --cache-to type=registry,ref=${cache_docker_tag}:cache \
              --tag ${docker_tag}
          fi
        done
